fix amd64 -> aarch64 cross compile for freebsd
- delete build-release and use build.yml for everything
- improve performance of repeated vagrant builds

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,6 +1,11 @@
-name: Build Binaries
+name: Build and Optionally Release Binaries
 
-on: [pull_request]
+on:
+  push:
+    branches: [main]
+  pull_request:
+  release:
+    types: [created]
 
 env:
   LIBPCAP_VERSION: 1.10.3
@@ -281,22 +286,83 @@ jobs:
                   aarch64-binutils arm-gnueabi-binutils amd64-binutils \
                   aarch64-freebsd-sysroot amd64-freebsd-sysroot armv7-freebsd-sysroot 
             run: |
-                ls -la /usr/local/bin
-                export PATH=/usr/local/bin:$PATH
                 go version
                 # fix for "fatal: detected dubious ownership in repository"
                 git config --global --add safe.directory /home/runner/work/udp-proxy-2020/udp-proxy-2020
-                FREEBSD_VERSION=${{ env.FREEBSD_VERSION }} gmake FREEBSD_ARCHES="amd64 arm64 arm7" freebsd-binaries
+                FREEBSD_VERSION=${{ env.FREEBSD_VERSION }} gmake FREEBSD_ARCHES="amd64 arm64 armv7" freebsd-binaries
 
         - name: Verify FreeBSD artifacts
           run: |
             ls -l dist/udp-proxy-2020*-freebsd-* || true
             ls dist/udp-proxy-2020*-freebsd-amd64 >/dev/null 2>&1 || { echo "Missing FreeBSD amd64 artifact"; exit 1; }
             ls dist/udp-proxy-2020*-freebsd-arm64 >/dev/null 2>&1 || { echo "Missing FreeBSD arm64 artifact"; exit 1; }
-            ls dist/udp-proxy-2020*-freebsd-arm7 >/dev/null 2>&1 || { echo "Missing FreeBSD armv7 artifact"; exit 1; }
+            ls dist/udp-proxy-2020*-freebsd-armv7 >/dev/null 2>&1 || { echo "Missing FreeBSD armv7 artifact"; exit 1; }
         # Artifacts docs: https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts
         - name: Upload files as artifact
           uses: actions/upload-artifact@v7
           with:
             name: build-files-freebsd
             path: dist/udp-proxy-2020*
+  sign-and-upload-files:
+    name: Sign and upload binary files
+    runs-on: ubuntu-latest
+    if: github.event_name == 'release'
+
+    # Wait for binary files to be built
+    needs: [linux-arm32, linux-aarch64, linux-amd64, linux-mips64, macos, freebsd]
+
+    steps:
+      - name: Download binaries linux-arm32
+        uses: actions/download-artifact@v6
+        with:
+          name: build-files-linux-arm32
+          path: dist/
+
+      - name: Download binaries linux-aarch64
+        uses: actions/download-artifact@v6
+        with:
+          name: build-files-linux-aarch64
+          path: dist/
+
+      - name: Download binaries linux-amd64
+        uses: actions/download-artifact@v6
+        with:
+          name: build-files-linux-amd64
+          path: dist/
+
+      - name: Download binaries linux-mips64
+        uses: actions/download-artifact@v6
+        with:
+          name: build-files-linux-mips64
+          path: dist/
+
+      - name: Download binaries macos
+        uses: actions/download-artifact@v6
+        with:
+          name: build-files-macos
+          path: dist/
+
+      - name: Download binaries freebsd
+        uses: actions/download-artifact@v6
+        with:
+          name: build-files-freebsd
+          path: dist/
+
+#      # Source: https://github.com/crazy-max/ghaction-import-gpg
+#      - name: Import GPG key
+#        uses: crazy-max/ghaction-import-gpg@v6.3.0
+#        with:
+#          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
+#          passphrase: ${{ secrets.GPG_PASSPHRASE }}
+#
+#      - name: Create signature file
+#        run: |
+#          shasum -a 256 dist/* | gpg --clear-sign > dist/release.sig.asc
+
+      # Source: https://github.com/svenstaro/upload-release-action
+      - name: Upload all files to release
+        uses: svenstaro/upload-release-action@v2
+        with:
+          file: dist/*
+          overwrite: true
+          file_glob: true
